use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let suites = [
        (
            "parsing",
            PathBuf::from("tests/integration/sources/parsing"),
        ),
        (
            "typechecking",
            PathBuf::from("tests/integration/sources/typechecking"),
        ),
        (
            "evaluator",
            PathBuf::from("tests/integration/sources/evaluator"),
        ),
        (
            "module_loading",
            PathBuf::from("tests/integration/sources/module_loading"),
        ),
        (
            "module_semantics",
            PathBuf::from("tests/integration/sources/module_semantics"),
        ),
    ];

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs\n");

    for (suite, relative_root) in suites {
        let root = manifest_dir.join(&relative_root);
        println!("cargo:rerun-if-changed={}", root.display());
        if !root.exists() {
            continue;
        }

        let fixtures = discover_suite_fixtures(suite, &root);
        for fixture in fixtures {
            let test_name = build_test_name(suite, &root, &fixture);
            let relative = fixture
                .strip_prefix(&manifest_dir)
                .expect("fixture path should be under manifest dir");
            let relative_str = relative.to_string_lossy().replace('\\', "/");
            generated.push_str(&format!(
                "register_integration_test!({}, \"{}\", \"{}\");\n",
                test_name, suite, relative_str
            ));
        }
    }

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("integration_generated.rs"), generated)
        .expect("failed to write generated integration tests");

    generate_embedded_stdlib(&manifest_dir, &out_dir);
}

/// Embed every `stdlib/**/*.mtl` file into the binary as a `(module_path, source)`
/// table consumed by `EmbeddedStdlibProvider` (METEL-181). A file at
/// `stdlib/core.mtl` becomes module path `["std", "core"]`; `stdlib/foo/bar.mtl`
/// becomes `["std", "foo", "bar"]`.
fn generate_embedded_stdlib(manifest_dir: &Path, out_dir: &Path) {
    let root = manifest_dir.join("stdlib");
    println!("cargo:rerun-if-changed={}", root.display());

    let mut entries = String::new();
    entries.push_str("// @generated by build.rs — embedded std:: sources\n");
    entries.push_str("pub static EMBEDDED_STDLIB: &[(&[&str], &str)] = &[\n");

    if root.exists() {
        let mut files = Vec::new();
        collect_mtl_files(&root, &mut files);
        files.sort();
        for file in files {
            let rel = file.strip_prefix(&root).expect("under stdlib root");
            // Path segments without the `.mtl` extension, prefixed with `std`.
            let mut segs: Vec<String> = vec!["std".to_string()];
            for comp in rel.with_extension("").components() {
                segs.push(comp.as_os_str().to_string_lossy().replace('\\', "/"));
            }
            let seg_lits = segs
                .iter()
                .map(|s| format!("{s:?}"))
                .collect::<Vec<_>>()
                .join(", ");
            let abs = file.to_string_lossy().replace('\\', "/");
            entries.push_str(&format!(
                "    (&[{seg_lits}], include_str!({abs:?})),\n"
            ));
        }
    }

    entries.push_str("];\n");
    fs::write(out_dir.join("stdlib_embedded.rs"), entries)
        .expect("failed to write generated embedded stdlib");
}

fn collect_mtl_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(read) = fs::read_dir(dir) else { return };
    for entry in read.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_mtl_files(&path, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some("mtl") {
            out.push(path);
        }
    }
}

fn discover_suite_fixtures(suite: &str, root: &Path) -> Vec<PathBuf> {
    let mut fixtures = Vec::new();
    discover_dir(suite, root, &mut fixtures);
    fixtures.sort();
    fixtures
}

fn discover_dir(suite: &str, dir: &Path, fixtures: &mut Vec<PathBuf>) {
    if is_multi_module_fixture(dir) {
        fixtures.push(dir.to_path_buf());
        return;
    }

    let mut entries: Vec<_> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", dir.display()))
        .map(|entry| {
            entry.unwrap_or_else(|e| panic!("failed to read dir entry in {}: {e}", dir.display()))
        })
        .collect();
    entries.sort_by_key(|entry| entry.path());

    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            discover_dir(suite, &path, fixtures);
            continue;
        }

        if path.extension().and_then(|ext| ext.to_str()) != Some("mtl") {
            continue;
        }

        if suite == "parsing"
            && path
                .file_stem()
                .and_then(|stem| stem.to_str())
                .is_some_and(|stem| stem.starts_with("neg_"))
        {
            continue;
        }

        fixtures.push(path);
    }
}

fn is_multi_module_fixture(dir: &Path) -> bool {
    dir.join("main.mtl").is_file()
}

fn build_test_name(suite: &str, root: &Path, fixture: &Path) -> String {
    let relative = fixture
        .strip_prefix(root)
        .expect("fixture should live under suite root");

    let mut parts = vec![suite.to_string()];
    if fixture.is_dir() {
        parts.extend(
            relative
                .components()
                .map(|component| component.as_os_str().to_string_lossy().into_owned()),
        );
    } else {
        if let Some(parent) = relative.parent() {
            parts.extend(
                parent
                    .components()
                    .map(|component| component.as_os_str().to_string_lossy().into_owned()),
            );
        }
        parts.push(
            relative
                .file_stem()
                .expect("fixture file should have stem")
                .to_string_lossy()
                .into_owned(),
        );
    }

    let joined = parts.join("__");
    sanitize_ident(&joined)
}

fn sanitize_ident(raw: &str) -> String {
    let mut out = String::new();
    for ch in raw.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push('_');
        }
    }

    if out.is_empty() || out.starts_with(|ch: char| ch.is_ascii_digit()) {
        out.insert_str(0, "case_");
    }

    out
}
