use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

/// Generate one `register_integration_test!` per line of the checked-in fixture
/// manifest (`tests/integration/fixtures.manifest`).
///
/// The manifest — not the fixture directories — is what this script watches, so
/// editing a fixture's *contents* rebuilds nothing (metel-core#873). The
/// manifest changes only when a fixture is added / removed / renamed, and the
/// `fixtures_manifest_is_current` test fails (with the regen command) if it
/// drifts from what's on disk, keeping discovery automatic in practice.
fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let manifest = manifest_dir.join("tests/integration/fixtures.manifest");
    println!("cargo:rerun-if-changed={}", manifest.display());

    let text = fs::read_to_string(&manifest).unwrap_or_else(|e| {
        panic!(
            "cannot read {}: {e}\n\
             run `UPDATE_FIXTURES=1 cargo test -p metel --test integration fixtures_manifest_is_current` to create it",
            manifest.display()
        )
    });

    let mut generated =
        String::from("// @generated by build.rs from tests/integration/fixtures.manifest\n");
    for (lineno, line) in text.lines().enumerate() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut cols = line.split('\t');
        let (Some(suite), Some(name), Some(path), None) =
            (cols.next(), cols.next(), cols.next(), cols.next())
        else {
            panic!(
                "{}:{}: expected `suite<TAB>test_name<TAB>relative_path`, got {line:?}",
                manifest.display(),
                lineno + 1
            );
        };
        let _ = writeln!(
            generated,
            "register_integration_test!({name}, {suite:?}, {path:?});"
        );
    }

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("integration_generated.rs");
    // Only touch the file `integration.rs` `include!`s when the list changed.
    if fs::read_to_string(&out_path).is_ok_and(|existing| existing == generated) {
        return;
    }
    fs::write(&out_path, generated).expect("failed to write generated integration tests");
}
