use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest"));
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("out dir"));
    let root = manifest_dir.join("stdlib");
    println!("cargo:rerun-if-changed={}", root.display());
    let mut entries = String::from("// @generated by build.rs — embedded std:: sources\n");
    entries.push_str("pub static EMBEDDED_STDLIB: &[(&[&str], &str)] = &[\n");
    let mut files = Vec::new();
    collect_mtl_files(&root, &mut files);
    files.sort();
    for file in files {
        let rel = file.strip_prefix(&root).expect("under stdlib root");
        let mut segs = vec!["std".to_string()];
        for component in rel.with_extension("").components() {
            segs.push(component.as_os_str().to_string_lossy().into_owned());
        }
        let seg_lits = segs
            .iter()
            .map(|s| format!("{s:?}"))
            .collect::<Vec<_>>()
            .join(", ");
        let abs = file.to_string_lossy().replace('\\', "/");
        writeln!(entries, "    (&[{seg_lits}], include_str!({abs:?})),").expect("write entry");
    }
    entries.push_str("];\n");
    fs::write(out_dir.join("stdlib_embedded.rs"), entries).expect("write embedded stdlib");
}

fn collect_mtl_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(read) = fs::read_dir(dir) else { return };
    for entry in read.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_mtl_files(&path, out);
        } else if path.extension().and_then(|ext| ext.to_str()) == Some("mtl") {
            out.push(path);
        }
    }
}
